version: '3'

services:
  json-cacher:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount config.json for configuration
      - ./config.json:/app/config.json
      # Mount cache for persistence between restarts
      - ./data:/app/data
    restart: unless-stopped 